name: dispatch workflow
on:
  repository_dispatch:
    types: [test]
  # workflow_dispatch:
  #   inputs:
  #     version:
  #       required: true
  #       description: This is a version

jobs:
  job1:
    name: dispatch trial
    runs-on: ubuntu-latest
    steps:
      - run: echo "success :)"
